default: true
line-length:
  line_length: 92
  heading_line_length: 80
  code_block_line_length: 80
  code_blocks: true
  tables: true
  headings: true
  headers: true
  strict: false
  stern: false
no-inline-html: false
first-line-h1: false